### ISSUE TITLE
Incorrect documentation for CorsResourcePolicy

### ISSUE THREAD

**Issue by centromere** [larskuhtz/wai-cors#23]
The [documentation](https://stackage.org/haddock/lts-13.13/wai-cors-0.2.6/Network-Wai-Middleware-Cors.html#t:CorsResourcePolicy) for `corsOrigins` states:

> A value other than `Nothing` is a tuple that consists of a list of origins each with a Boolean flag that indicates if credentials are used to access the resource via CORS.

Its type is: `!(Maybe ([Origin], Bool))`

This type does not permit associating a Boolean flag _with each_ origin. The way the text reads, the type should be:

`!(Maybe [(Origin, Bool)])`

**Comment by larskuhtz** [comment]
Thanks for noting this inconsistency. It turns out that the documentation is wrong. The [CORS Resource Processing Model](https://www.w3.org/TR/cors/#resource-processing-model) states that the flag is associated with the resource and not with the origin:

> For the purposes of this section each resource is bound to the following:
> [...]
> A supports credentials flag that indicates whether the resource supports user credentials in the request. It is true when the resource does and false otherwise.

The reason that the flag doesn't occupy a policy field on it's own but is included in the `corsOrigin` field is that is only meaningful if the value of `corsOrigin` is not `Nothing`:

> The string "*" cannot be used for a resource that supports credentials.
